use std::fmt::Debug;

use proptest::prelude::*;
use proptest::strategy::BoxedStrategy;
use proptest_state_machine::{ReferenceStateMachine, StateMachineTest};

use crate::action::AnyAction;
use crate::env::TypedEnv;
use crate::model::LockstepModel;

// ---------------------------------------------------------------------------
// Reference state machine (model side)
// ---------------------------------------------------------------------------

/// The reference state machine wrapping a `LockstepModel`.
#[derive(Debug)]
pub struct LockstepRef<M: LockstepModel> {
    pub model: M::ModelState,
    pub model_env: TypedEnv,
    pub next_var_id: usize,
}

impl<M: LockstepModel> Clone for LockstepRef<M> {
    fn clone(&self) -> Self {
        LockstepRef {
            model: self.model.clone(),
            model_env: self.model_env.clone(),
            next_var_id: self.next_var_id,
        }
    }
}

impl<M: LockstepModel> ReferenceStateMachine for LockstepRef<M> {
    type State = Self;
    type Transition = Box<dyn AnyAction>;

    fn init_state() -> BoxedStrategy<Self::State> {
        Just(LockstepRef {
            model: M::init_model(),
            model_env: TypedEnv::new(),
            next_var_id: 0,
        })
        .boxed()
    }

    fn transitions(state: &Self::State) -> BoxedStrategy<Self::Transition> {
        M::gen_action(&state.model, &state.model_env)
    }

    fn apply(mut state: Self::State, transition: &Self::Transition) -> Self::State {
        // Step the model
        let var_id = state.next_var_id;
        let model_result =
            M::step_model(&mut state.model, transition.as_ref(), &state.model_env);

        // Store model variable (auto-generated by proc macro)
        transition.store_model_var(var_id, &*model_result, &mut state.model_env);
        state.next_var_id += 1;

        state
    }

    fn preconditions(state: &Self::State, transition: &Self::Transition) -> bool {
        let vars_ok = transition
            .used_vars()
            .iter()
            .all(|v| state.model_env.contains_raw(*v));

        vars_ok && M::precondition(&state.model, transition.as_ref(), &state.model_env)
    }
}

// ---------------------------------------------------------------------------
// SUT state machine
// ---------------------------------------------------------------------------

/// The concrete (SUT) side of the lockstep test.
///
/// Maintains its own copy of the model state and environment so that
/// the lockstep comparison is self-contained — no shared mutable state
/// with the reference side.
///
/// This means the model executes twice per step: once in
/// `ReferenceStateMachine::apply` (for state advancement and shrinking)
/// and once here (for lockstep comparison). Models should be cheap,
/// pure data structures — this is by design.
#[derive(Debug)]
pub struct LockstepSut<M: LockstepModel> {
    pub sut: M::Sut,
    pub real_env: TypedEnv,
    pub model_state: M::ModelState,
    pub model_env: TypedEnv,
    pub next_var_id: usize,
}

impl<M: LockstepModel> StateMachineTest for LockstepSut<M> {
    type SystemUnderTest = Self;
    type Reference = LockstepRef<M>;

    fn init_test(_ref_state: &LockstepRef<M>) -> Self::SystemUnderTest {
        LockstepSut {
            sut: M::init_sut(),
            real_env: TypedEnv::new(),
            model_state: M::init_model(),
            model_env: TypedEnv::new(),
            next_var_id: 0,
        }
    }

    fn apply(
        mut state: Self::SystemUnderTest,
        _ref_state: &LockstepRef<M>,
        transition: Box<dyn AnyAction>,
    ) -> Self::SystemUnderTest {
        // Run the model on the SUT side's own copy to get the result for comparison.
        let model_result = M::step_model(
            &mut state.model_state,
            transition.as_ref(),
            &state.model_env,
        );

        // Run SUT
        let sut_result =
            M::step_sut(&mut state.sut, transition.as_ref(), &state.real_env);

        // Lockstep check (auto-generated bridge dispatch)
        transition
            .check_bridge(&*model_result, &*sut_result)
            .unwrap_or_else(|msg| {
                panic!(
                    "Lockstep mismatch!\n  Action: {:?}\n{}",
                    transition, msg
                )
            });

        // Store variables
        let var_id = state.next_var_id;
        transition.store_model_var(var_id, &*model_result, &mut state.model_env);
        transition.store_sut_var(var_id, &*sut_result, &mut state.real_env);
        state.next_var_id += 1;

        state
    }
}

// ---------------------------------------------------------------------------
// Convenience test runner
// ---------------------------------------------------------------------------

/// Run a lockstep test with the given size range.
pub fn run_lockstep_test<M: LockstepModel>(
    size: impl Into<proptest::collection::SizeRange>,
) {
    let config = proptest::test_runner::Config::default();
    proptest::proptest!(config, |((initial_state, transitions, seen_counter) in
        <LockstepRef<M> as ReferenceStateMachine>::sequential_strategy(size))| {
        LockstepSut::<M>::test_sequential(
            proptest::test_runner::Config::default(),
            initial_state,
            transitions,
            seen_counter,
        );
    });
}

/// Run a lockstep test with custom configuration.
pub fn run_lockstep_test_with_config<M: LockstepModel>(
    config: proptest::test_runner::Config,
    size: impl Into<proptest::collection::SizeRange>,
) {
    let inner_config = config.clone();
    proptest::proptest!(config, |((initial_state, transitions, seen_counter) in
        <LockstepRef<M> as ReferenceStateMachine>::sequential_strategy(size))| {
        LockstepSut::<M>::test_sequential(
            inner_config.clone(),
            initial_state,
            transitions,
            seen_counter,
        );
    });
}
